version: '3.3'

services:
 frontend:
  image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-frontend:latest
  restart: always
  container_name: sausage-store-frontend
  networks:
    - net-sausage-store
  ports:
    - '80:80'

 backend:
  image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-backend:latest
  restart: always
  container_name: sausage-store-backend
  environment:
    - DATA_SOURCE_CONNECT=$DATA_SOURCE_CONNECT
    - DATA_SOURCE_NAME=$DATA_SOURCE_NAME
    - DATA_SOURCE_PASS=$DATA_SOURCE_PASS
    - MONGO_CONNECT=$MONGO_CONNECT
  networks:
    - net-sausage-store

networks:
 net-sausage-store:
  driver: bridge
