version: '3.3'

services:
 frontend:
  image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-frontend:latest
  restart: always
  container_name: sausage-store-frontend

  ports:
    - '80:80'

 backend:
  image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-backend:latest
  restart: always
  container_name: sausage-store-backend

  ports:
    - '8080:8080'

networks:
  frontend:
    driver: custom-driver-1
  backend:
    driver: custom-driver-1
