version: '3.8'

services:
 frontend:
  build: ./frontend
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-frontend:latest
  restart: always
  container_name: sausage-store-frontend

  ports:
    - '80:80'

 backend:
  build: ./backend
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}-backend:latest
  restart: always
  container_name: sausage-store-backend

  ports:
    - '8080:8080'

networks:
  frontend:
    name: sausage-store
    driver: custom-driver-1
  backend:
    name: sausage-store
    driver: custom-driver-1
