version: '3.3'

services:
 vault:
  image: vault:1.9.3
  restart: always
  container_name: vault
  ports:
    - '8200:8200'
  environment:
    VAULT_DEV_ROOT_TOKEN_ID: "myroot"
    VAULT_SERVER: "http://vault:8200"
    VAULT_ADDR: "http://vault:8200"
  networks:
    - net-sausage-store

 frontend:
  image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-frontend:latest
  restart: always
  container_name: sausage-store-frontend
  networks:
    - net-sausage-store
  ports:
    - '80:80'
    - '8080:8080'

 backend:
  image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-backend:latest
  restart: always
  container_name: sausage-store-backend
  environment:
    SPRING_CLOUD_VAULT_TOKEN: $SPRING_CLOUD_VAULT_TOKEN
    SPRING_CLOUD_VAULT_HOST: $SPRING_CLOUD_VAULT_HOST
    SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
    SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
    #SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    SPRING_DATA_MONGODB_URI: $SPRING_DATA_MONGODB_URI
  networks:
    - net-sausage-store

networks:
 net-sausage-store:
  driver: bridge
